apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    # This database should be mapped to a bucket
    database: gatlingdb
    basicAuth: false
    isDefault: true
    editable: true
