{
 "title": "Reporte Gatling g7",
 "description": "Gatling statistics review\n",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "data source", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "SHOW RETENTION POLICIES" },
   { "name": "new", "label": "Retention policy (new)", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "simulation",
    "label": "Simulation",
    "query": "SELECT DISTINCT(\"simulation\") FROM \n  (SELECT last(\"mean\") FROM \"$new\".\"gatling\" GROUP BY \"simulation\"),\n  (SELECT last(\"mean\") FROM \"$archive\".\"gatling\" GROUP BY \"simulation\")\nWHERE $timeFilter"
   },
   {
    "name": "mean_max",
    "query": "SELECT max(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"autogen\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "mean_mean",
    "query": "SELECT mean(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"autogen\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "mean_median",
    "query": "SELECT median(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"autogen\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "duration_median",
    "query": "SELECT median(\"Duration\") FROM (\nSELECT SUM(\"e\") as \"Duration\" FROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT sum(\"count\") AS \"KO\" FROM \"gatling\" WHERE (\"status\" = 'ko') AND $timeFilter GROUP BY \"simulation\",  \"request\""
    },
    {
     "query": "SELECT sum(\"count\") AS \"KO\" FROM \"gatling\" WHERE (\"status\" = 'ko') AND $timeFilter GROUP BY \"simulation\" , \"request\""
    }
   ]
  },
  {
   "title": "Response Time Percentiles over Time (OK)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "query": "SELECT percentile(\"percentiles50\", 50) AS \"50%\", percentile(\"percentiles95\", 95) AS \"95%\", percentile(\"percentiles99\", 99) AS \"99%\", max(\"max\") AS \"max\", percentile(\"percentiles75\", 75) AS \"75%\", min(\"min\") AS \"min\"  FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok' AND \"simulation\" =~ /^$simulation$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT sum(\"active\") FROM \"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers') AND $timeFilter GROUP BY time($__interval), \"simulation\""
    }
   ]
  },
  {
   "title": "Test: %OK and %Fail ",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "OK" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_median}" ], "type": "math" },
       { "params": [ "Mean / median(Mean)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Duration\", \"Duration\" / ${duration_median} as \"Duration / median(Duration)\",  \"run\"\nFROM (\nSELECT SUM(\"e\") as \"Duration\" \nFROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"\n)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test: %OK and %Fail ",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") AS \"OK\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok' AND \"simulation\" =~ /^$simulation$/) AND $timeFilter GROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") AS \"KO\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ko' AND \"simulation\" =~ /^$simulation$/) AND $timeFilter GROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") AS \"Total\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'all' AND \"simulation\" =~ /^$simulation$/) AND $timeFilter GROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Mean Time + Mean analitics",
   "type": "table",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_max}" ], "type": "math" },
       { "params": [ "Mean / max(Mean)" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_mean}" ], "type": "math" },
       { "params": [ "Mean / mean(Mean)" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_median}" ], "type": "math" },
       { "params": [ "Mean / median(Mean)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  }
 ]
}